
stages:
  - test

test:
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: test
  script:
    - npm ci
    - npm run start:ci &
    - npx cypress run --browser firefox










# image: cypress/base:14.16.0

# stages:
#   - build
#   - e2e

# install:
#   image: cypress/base:14.16.0
#   stage: build

#   script:
#     - npm ci


# e2e-testing:
#   image: cypress/base:14.16.0
#   stage: e2e

#   script:
#     - npm test





# image: cypress/base:14.16.0

# stages:
#   -build
#   -test

# local-e2e:
#   stage: test

#   script:
#     - npm ci --prefer-offline
#     - npm start &
#     - npx cypress run